apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: gakrishn-operator-bundle-18-mar-2025-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
